/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as InglesRouteImport } from './routes/ingles'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as ApiPublicWebhookInfinitepayRouteImport } from './routes/api/public/webhook-infinitepay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InglesRoute = InglesRouteImport.update({
  id: '/ingles',
  path: '/ingles',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicWebhookInfinitepayRoute =
  ApiPublicWebhookInfinitepayRouteImport.update({
    id: '/api/public/webhook-infinitepay',
    path: '/api/public/webhook-infinitepay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/ingles': typeof InglesRoute
  '/thanks': typeof ThanksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/api/public/webhook-infinitepay': typeof ApiPublicWebhookInfinitepayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/ingles': typeof InglesRoute
  '/thanks': typeof ThanksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/api/public/webhook-infinitepay': typeof ApiPublicWebhookInfinitepayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/ingles': typeof InglesRoute
  '/thanks': typeof ThanksRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/api/public/webhook-infinitepay': typeof ApiPublicWebhookInfinitepayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ingles'
    | '/thanks'
    | '/dashboard'
    | '/admin/dashboard'
    | '/api/public/webhook-infinitepay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ingles'
    | '/thanks'
    | '/dashboard'
    | '/admin/dashboard'
    | '/api/public/webhook-infinitepay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/ingles'
    | '/thanks'
    | '/_authenticated/dashboard'
    | '/admin/dashboard'
    | '/api/public/webhook-infinitepay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  InglesRoute: typeof InglesRoute
  ThanksRoute: typeof ThanksRoute
  ApiPublicWebhookInfinitepayRoute: typeof ApiPublicWebhookInfinitepayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingles': {
      id: '/ingles'
      path: '/ingles'
      fullPath: '/ingles'
      preLoaderRoute: typeof InglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/webhook-infinitepay': {
      id: '/api/public/webhook-infinitepay'
      path: '/api/public/webhook-infinitepay'
      fullPath: '/api/public/webhook-infinitepay'
      preLoaderRoute: typeof ApiPublicWebhookInfinitepayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  InglesRoute: InglesRoute,
  ThanksRoute: ThanksRoute,
  ApiPublicWebhookInfinitepayRoute: ApiPublicWebhookInfinitepayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
