// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const SUPABASE_SERVICE_ROLE_KEY = process.env['SUPABASE_SERVICE_ROLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    console.warn(`[Supabase Admin] Configuração incompleta. URL: ${!!SUPABASE_URL}, Key: ${!!SUPABASE_SERVICE_ROLE_KEY}`);
    return null;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: any | undefined;

export const supabaseAdmin = new Proxy({} as any, {
  get(_, prop, receiver) {
    if (_supabaseAdmin === undefined) _supabaseAdmin = createSupabaseAdminClient();
    
    if (_supabaseAdmin === null) {
      // Se for a propriedade 'auth', 'from', etc, retornamos um proxy recursivo
      // para evitar erros de "cannot read property 'login' of undefined"
      const dummy = (...args: any[]) => {
        console.error(`ERRO CRÍTICO: Tentativa de usar supabaseAdmin.${String(prop)} sem SUPABASE_SERVICE_ROLE_KEY.`);
        return { 
          data: null, 
          error: { message: "Configuração de servidor ausente (SERVICE_ROLE_KEY)." },
          select: () => ({ 
            data: null, 
            error: { message: "Configuração de servidor ausente." },
            single: () => ({ data: null, error: { message: "Configuração de servidor ausente." } }),
            maybeSingle: () => ({ data: null, error: { message: "Configuração de servidor ausente." } }),
            order: () => ({ 
              data: null, 
              error: { message: "Configuração de servidor ausente." },
              limit: () => ({ data: null, error: { message: "Configuração de servidor ausente." } })
            }),
            limit: () => ({ data: null, error: { message: "Configuração de servidor ausente." } })
          }),
          insert: () => ({ data: null, error: { message: "Configuração de servidor ausente." } }),
          update: () => ({ data: null, error: { message: "Configuração de servidor ausente." } }),
          delete: () => ({ data: null, error: { message: "Configuração de servidor ausente." } }),
          upsert: () => ({ data: null, error: { message: "Configuração de servidor ausente." } }),
          rpc: () => ({ data: null, error: { message: "Configuração de servidor ausente." } }),
          auth: {
            admin: new Proxy({}, { get: () => dummy }),
            signInWithPassword: async () => ({ data: { user: null, session: null }, error: { message: "Configuração de servidor ausente." } }),
          },
          storage: {
            from: () => ({
              createSignedUrl: async () => ({ data: null, error: { message: "Configuração de servidor ausente." } }),
              upload: async () => ({ data: null, error: { message: "Configuração de servidor ausente." } }),
              download: async () => ({ data: null, error: { message: "Configuração de servidor ausente." } }),
            })
          },
          from: () => ({
            select: () => ({ 
              data: null, 
              error: { message: "Configuração de servidor ausente." },
              eq: () => ({ 
                data: null, 
                error: { message: "Configuração de servidor ausente." },
                single: () => ({ data: null, error: { message: "Configuração de servidor ausente." } }),
                maybeSingle: () => ({ data: null, error: { message: "Configuração de servidor ausente." } }),
                order: () => ({ data: null, error: { message: "Configuração de servidor ausente." } })
              }),
              order: () => ({ 
                data: null, 
                error: { message: "Configuração de servidor ausente." },
                limit: () => ({ data: null, error: { message: "Configuração de servidor ausente." } })
              })
            })
          })
        };
      };
      
      if (['auth', 'storage', 'from'].includes(prop as string)) {
        const dummyObj = dummy();
        return (dummyObj as any)[prop];
      }
      
      return dummy;
    }
      
      return dummy;
    }
    
    const value = Reflect.get(_supabaseAdmin, prop, receiver);
    if (typeof value === 'function') {
      return value.bind(_supabaseAdmin);
    }
    return value;
  },
});
